version: "3"
services:

  database:
      image: mysql:5.7
      command: --character-set-server=utf8 --collation-server=utf8_general_ci
      ports:
          - 3386:3306
      volumes:
          - ./data/:/var/lib/mysql
      environment:
          MYSQL_DATABASE: demo
          MYSQL_USER: root
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: password
